---
title: "Yuri Silva de Souza"
author: Yuri Silva de Souza
date: "`r Sys.Date()`"
output:
  pagedown::html_resume:
    # set it to true for a self-contained HTML page but it'll take longer to render
    self_contained: true
    css: resume.css
---

Aside
================================================================================

Contact {#contact}
--------------------------------------------------------------------------------
- `Room 204, Cox Science Building, 1301 Memorial Dr, Coral Gables, FL 33146`
-  _______________
- `r icons::fontawesome("link")` [`souzayuri.github.io`](https://souzayuri.github.io/)
- `r icons::fontawesome("envelope", style = "solid")` `desouza.s.yuri@gmail.com`
- `r icons::fontawesome("twitter")` [`Yuri_S_Souza`](https://twitter.com/Yuri_S_Souza)
- `r icons::fontawesome("github")` [`github.com/souzayuri`](https://github.com/souzayuri)
- `r icons::academicons("researchgate")` [`Researchgate`](https://www.researchgate.net/profile/Yuri-Souza-6)
- `r icons::academicons("google-scholar")` [`Google Citations`](https://scholar.google.com.br/citations?user=s1YL0toAAAAJ&hl=en)
- `r icons::fontawesome("orcid")` [`0000-0002-2133-0469`](https://orcid.org/0000-0002-2133-0469)

Themes {#themes}
--------------------------------------------------------------------------------

- `r icons::fontawesome("paw")` `Convervation biology`
- `r icons::fontawesome("globe-americas")` `Community Ecology`
- `r icons::fontawesome("seedling")` `Population Ecology`
- `r icons::fontawesome("mountain")` `Landscape Ecology`
- `r icons::fontawesome("layer-group")` `Geoprocessing`
- `r icons::fontawesome("compass")` `Fieldwork`
- `r icons::fontawesome("chart-bar")` `DataScience`

Skills {#skills}
--------------------------------------------------------------------------------

- `r icons::fontawesome("r-project")` [`R (Advanced)`](https://www.r-project.org/)
- `r icons::fontawesome("laptop-code")` [`tidyverse (Advanced)`](https://www.tidyverse.org/)
- `r icons::fontawesome("cube")` [`ShinyR (Intermediate)`](https://shiny.rstudio.com/)
- `r icons::academicons("academia")` [`ArcGis (Intermediate`)](https://qgis.org/en/site/)
- `r icons::fontawesome("python")` [`python (Basic)`](https://www.python.org/)
- `r icons::fontawesome("code-branch")` [`git (Basic)`](https://git-scm.com/)
- `r icons::fontawesome("database")` [`MySQL (Basic)`](https://www.mysql.com/)

Languages {#languages}
--------------------------------------------------------------------------------
- Portuguese (Native speaker)
- English (Advanced)

Main
================================================================================

Yuri Souza {#title}
--------------------------------------------------------------------------------

### Doctoral Student in Biology

I am a tropical Ecologist with a broad interest in community and ecosystem dynamics. My experiences range from fieldwork to statistics and data analyses. My current interest relies on understanding the dynamics above and below-ground processes and their consequences on ecosystem maintenance.

Education {data-icon=graduation-cap}
--------------------------------------------------------------------------------

### University of Miami (UM)

[Doctoral Student in Biology](https://welcome.miami.edu/)

Miami, FL, United States

2022 - Present

**Advisor**: Dr. [Amy Zanne](http://amyzanne.org/)

### University of Sao Paulo (USP)

[MBA in Data Science and Analytics](https://academico.pecege.org.br/CourseClass/GetDeclaration?courseRegistrationId=258272&cultureInfo=en-us)

Piracicaba, SP, Brazil

2022 - Present

**Thesis**: ShinyApp application as a tool for ecological data management, analyses, visualization, and digital decision making approach ([Aplication Result](https://souzayuri.shinyapps.io/reseedproject))                                       
**Advisor**: Dr. [Walter Mesquita Filho](https://scholar.google.com/citations?user=T0d2ZS4AAAAJ&hl=en)

### São Paulo State University (UNESP)

[Master in Ecology and Biodiversity](https://ib.rc.unesp.br/#!/pos-graduacao/secao-tecnica-de-pos/programas2546/)

Rio Claro, SP, Brazil

2018 - 2021

**Thesis**: Large mammalian herbivores modulate plant growth form diversity in a tropical rainforest ([UNESP Libraries](https://repositorio.unesp.br/handle/11449/234138))  
**Advisor**: Dr. [Mauro Galetti](https://scholar.google.com/citations?user=8zr5fEMAAAAJ&hl=en)

### São Paulo State University (UNESP)

[Bachelor in Ecology](https://ib.rc.unesp.br/#!/graduacao/cursos-conselho-de-curso/ecologia/)

Rio Claro, SP, Brazil

2013 - 2016

**Thesis**: Uma análise de modelagem do ciclo hidrológico e impactos do aumento da concentração de CO2 atmosférico na Amazônia ([UNESP Libraries](https://repositorio.unesp.br/handle/11449/155815))  
**Advisor**: Dr. [David Montenegro Lapola](https://aimesproject.org/david-lapola/)

Complementary Education {data-icon=chalkboard}
--------------------------------------------------------------------------------

### Multivariate Analysis using R

e-MultivaR (Online)

Florianópolis, SC, Brazil

2020

::: concise
- 22 h 
- [course](https://easyr.com.br/e-multivar)
:::

### Hierarchical Modelling of Species Communities with the R-package Hmsc

University of Helsinki (Online)

Helsinki, Finland

2020

::: concise
- 25 h 
- [course](https://www.helsinki.fi/en/researchgroups/statistical-ecology/hmsc)
:::

### Introduction to Hierarchical Modeling

Federal University of Rio Grande do Sul (UFRGS)

Porto Alegre, RS, Brazil

2019

::: concise
- 45 h 
- [course](http://ferrazlab.org/graduate)
:::

### Introduction of R: data management, visualization and analysis

LaBic - UNESP

Rio Claro, SP, Brazil

2019

::: concise
- 40 h 
- [course](https://mauriciovancine.github.io/teaching/workshop-intror/)
:::

### Geographic information system in the analysis of environmental risks using ArcGIS software 

Geoprocessing with no boundaries (online)

Rio de Janeiro, RJ, Brazil

2017

::: concise
- 16 h 
- [course](https://geosemfronteiras.org/analista-em-gis-com-arcgis/)
:::

Scholarship & Awards {data-icon=award}
--------------------------------------------------------------------------------

### Doctoral Graduate Fellowship

[Dean's fellowship](https://news.miami.edu/grad/stories/2021/09/congrats-2021-2022-new-grad-fellows.html) (US$ 72.000,00)  
University of Miami (UM)  

Miami, FL, United States

2022 - 2024

### Master Graduate International Fellowship

Sao Paulo Research Foundation (FAPESP) (US$ 9.636,00)  
São Paulo State University (UNESP)  
Grant [#2019/20905-4](https://bv.fapesp.br/en/bolsas/186517/influence-of-defaunation-on-the-dynamics-of-tropical-plant-life-forms/)

Rio Claro, SP, Brazil

2020 - 2021

**Title**: 	The effects of defaunation on carbon stock in plant functional groups in the Atlantic forest  
**Aim**: 1- Access the carbon content in plant growth form saplings in different growth stages; 2- Investigate how Defaunation might affect plant carbon content

### Master Graduate Scholarship

Sao Paulo Research Foundation (FAPESP) (BRL 48,852.54)  
São Paulo State University (UNESP)  
Grant [#19/05538-5](https://bv.fapesp.br/en/bolsas/186517/influence-of-defaunation-on-the-dynamics-of-tropical-plant-life-forms/)

Rio Claro, SP, Brazil

2018 - 2021

**Title**: Large mammalian herbivores modulate plant growth form diversity in a tropical rainforest  
**Aim**: 1- Investigate how the extinction of large mammalian herbivores might affect plant growth form community by changes plant composition, interactions and diversity; 2- Address the consequences of these changes to the tropical forest

### Scientific Initiation Scholarship

Sao Paulo Research Foundation (FAPESP) (BRL 7,960.00)  
São Paulo State University (UNESP)  
Grant [#15/03759-3](https://bv.fapesp.br/en/bolsas/162201/an-analysis-modeling-of-the-hydrological-cycle-and-impacts-of-increased-atmospheric-co2-concentratio/)

Rio Claro, SP, Brazil

2016

**Title**: An analysis modeling of the hydrological cycle and impacts of increased atmospheric CO2 concentration in the Amazon  
**Aim**: 1- Validation and calibration of a water balance model using updated input data; 2- application of this model in the Amazon forest, in line with the [AmazonFACE](https://amazonface.inpa.gov.br/en/index.php) project, seeking to improve understanding of the effects of increased CO2 in the water dynamics of this biome

Research Experience {data-icon=laptop}
--------------------------------------------------------------------------------

### Technical Training

Sao Paulo Research Foundation (FAPESP) (BRL 13,021.60)  
São Paulo State University (UNESP)  
Grant [#21/08509-6](https://bv.fapesp.br/en/bolsas/197712/curatorship-processing-and-synthesis-of-seed-dispersal-traits-of-plants-and-animals-from-literature-/)

Rio Claro, SP, Brazil

2021 - 2022

**Title**: Curatorship, processing and synthesis of seed dispersal traits of plants and animals from literature and field data  
**Aim**: 1- Creating an online platform for plant traits data input; 2- Create a platform for [data manipulation, analysis, and visualization](https://souzayuri.shinyapps.io/reseedproject/)

::: concise
- 2000 h 
:::

Professional Experience {data-icon=suitcase}
--------------------------------------------------------------------------------

### Environmental consultant

[University of Miami](https://biology.as.miami.edu/people/graduate-students/index.html)

Miami, FL, United States

2021 - 2022

::: concise
- Fieldwork collection & assistant
- Plots construction
:::

### Environmental consultant

[LaBic](https://ib.rc.unesp.br/#!/departamentos/ecologia/labic/home/)

Rio Claro, SP, Brazil

2018

::: concise
- Landscape cover
- Mapping
- Land use
:::

### Environmental consultant

[LaBic](https://ib.rc.unesp.br/#!/departamentos/ecologia/labic/home/)

Rio Claro, SP, Brazil

2017 - 2018

::: concise
- Fieldwork assistant
- Camera Trap installation 
:::

### Environmental consultant

[São Paulo State University](https://unesp.br/portaldocentes/docentes/67646?lang=pt_BR)

Botucatu, SP, Brazil

2017 - 2018

::: concise
- GIS tutorial
- Map production 
:::

### Environmental consultant

[Itirapina Ecological Station](https://www.infraestruturameioambiente.sp.gov.br/institutoflorestal/areas-protegidas/estacoes-ecologicas/itirapina/)

Itirapina, SP, Brazil

2017

::: concise
- GIS analist
- Invasive specie controlling 
:::

Teaching Experience {data-icon=chalkboard-teacher}
--------------------------------------------------------------------------------
### <u>Graduation</u>

N/A

N/A

### 01. Fortran mondelling and ArcGIS visualization

Teacher Assistant 
*Graduate in Ecology and Biodiversity*
Environmental Changing classes
São Paulo State University (UNESP)

Rio Claro, SP, Brazil

2014

::: concise
- 8 h
:::

### <u>Undergraduation</u>

N/A

N/A

### 02. R-based statistics applied to ecology fieldwork 

Teacher Assistant 
*Undergraduate in Ecology*
Fieldwork Ecology classes
São Paulo State University (UNESP)

Rio Claro, SP, Brazil

2018

::: concise
- 16 h
:::

### 01. Savanna fieldwork sample design experiment

Teacher Assistant 
*Undergraduate in Environmental Science*
Biogeography for Environmental Management and Analysis classes
Federal University of São Carlos (UFSCar)

São Carlos, SP, Brazil

2018

::: concise
- 48 h
:::

Books {data-icon=book}
--------------------------------------------------------------------------------

### 01. The Atlantic Forest History, Biodiversity, Threats and Opportunities of the Mega-diverse Forest
*Chapter*: [Causes and Consequences of Large-Scale Defaunation in the Atlantic Forest](https://link.springer.com/chapter/10.1007/978-3-030-55322-7_14) 

*New York: Springer*

N/A

Galetti, Mauro; Gonçalves, Fernando; Villar, Nacho; Zipparro, Valesca; Paz, Claudia; Mendes, Calebe; Lautenschlager, Lais; <u>**Souza, Yuri**</u>; Akkawi, Paula; Pedrosa, Felipe;, Bulascoschi, Leticia; Bello, Carolina; Sevá, Anaiá P.; Sales, Lilian; Genes, Luísa; Abra, Fernanda; Bovendorp, Ricardo S. 2021, 297–324p, ISBN: 978-3-030-55322-7 

Publications {data-icon=file}
--------------------------------------------------------------------------------

### 06. Frugivory and seed dispersal by the Red-footed Tortoise *Chelonoidis carbonaria*

*Acta Oecologica*, 116: 103837

N/A

2022

DOI: [10.1016/j.actao.2022.103837](https://doi.org/10.1016/j.actao.2022.103837)
<br>
Lautenschlager, Lais; <u>**Souza, Yuri**</u>; Galetti, Mauro

### 05. Large mammalian herbivores modulate plant growth form diversity in a tropical rainforest

*Journal of Ecology*, 110(04), 845-859 p

N/A

2022

DOI: [10.1111/1365-2745.13846](https://doi.org/10.1111/1365-2745.13846)
<br>
<u>**Souza, Yuri**</u>; Villar, Nacho; Ziparro, Valesca; Nazareth, Sérgio; Galetti, Mauro

### 04. ATLANTIC MAMMALS: a data set of assemblages of medium and large-sized mammals of the Atlantic Forest of South America

*Ecology* 100(10), e02785

N/A

2019

DOI: [10.1002/ecy.2785](https://doi.org/10.1002/ecy.2785)
<br>
<u>**Souza, Yuri**</u>, *et al*. 

### 03. ATLANTIC AMPHIBIANS: a data set of amphibian communities from the Atlantic Forests of South America

*Ecology* 99(07), 1692-1692 p

N/A

2018

DOI: [10.1002/ecy.2392](https://doi.org/10.1002/ecy.2392)
<br>
Vancine, Maurício H.; Duarte, Kauã da Silva; <u>**De Souza, Yuri S.**</u>; Giovanelli, João G, R.; Martins- sobrinho, Paulo M.; López, Ariel; Bovo, Rafael P.; Maffei, Fábio; Lion, Marília B.; Ribeiro Júnior, José W.; Brassaloti, R.; Da Costa, Carolina O, R.; Sawakuchi, Henrique O.; Forti, Lucas R.; Cacciali, Pier; Bertoluci, Jaime; Haddad, Célio F, B.; Ribeiro, Milton C. 

### 02. Análise Temporal da Invasão Biológica de *Pinus sp.* em Área Úmida do Domínio Cerrado

*Revista Brasileira de Geografia Física* 11(02), 521-531 p

N/A

2018

DOI: [10.26848/rbgf.v11.2.p521-531](https://doi.org/10.26848/rbgf.v11.2.p521-531)
<br>
Conciani, Dhemerson; <u>**De Souza, Yuri S.**</u>; Ruffino, Paulo H, P.; Zanchetta, Denise

### 01. Uma aplicação de modelagem do ciclo hidrológico e impactos do aumento da concentração de CO2 atmosférico na Amazônia

*Revista UniVap* 

N/A

2016

DOI: [10.18066/revistaunivap.v22i40.477](http://dx.doi.org/10.18066/revistaunivap.v22i40.477)
<br>
<u>**Souza, Yuri S.**</u>; Lapola, David M. 


Disclaimer {#disclaimer}
------------------------------------
<i class='fas fa-file-pdf'></i> [Download PDF](https://github.com/souzayuri/cv/raw/main/cv-yuri-souza-en-academic-complete.pdf)
<br>

`CV by` [**`pagedown`**](https://github.com/rstudio/pagedown) R package.  
`Code available on` `r icons::fontawesome("github")` [GitHub](https://github.com/souzayuri/cv).  
 
`Last updated on` `r Sys.Date()`

